Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,6 +39,15 @@ jobs:
     - name: Terraform Apply
       run: terraform apply -auto-approve
 
+    - name: Check Terraform Apply Status
+      run: |
+        if [ ${{ steps.terraform_apply.outcome }} == "success" ]; then
+          echo "Terraform apply succeeded. Proceeding to the next steps."
+        else
+          echo "Terraform apply failed. Exiting the workflow."
+          exit 1
+        fi
+
     - name: Check for changes in Dev
       id: check_changes
       run: |
