Update pull_push.yml

diff --git a/.github/workflows/pull_push.yml b/.github/workflows/pull_push.yml
--- a/.github/workflows/pull_push.yml
+++ b/.github/workflows/pull_push.yml
@@ -47,14 +47,14 @@ jobs:
     
     - name: Update Databricks Notebook
       run: |
-        # Check if the file exists in DBFS
-        if databricks fs ls "dbfs:/tmp/ci_cd.py"; then
-          # Export and import the notebook in Databricks workspace
-          databricks workspace export -o "dbfs:/tmp/ci_cd.py" "workspace:/Users/shyamkumarr@jmangroup.com/cicd"
-          databricks workspace import -o "dbfs:/tmp/ci_cd.py" "workspace:/Users/shyamkumarr@jmangroup.com/cicd"
+        # Check if the file exists in DBFS (using absolute path)
+        if databricks fs ls "/dbfs/tmp/ci_cd.py"; then
+            # Export and import the notebook in Databricks workspace (using absolute paths)
+            databricks workspace export -o "/dbfs/tmp/ci_cd.py" "/Users/shyamkumarr@jmangroup.com/cicd"
+            databricks workspace import -o "/dbfs/tmp/ci_cd.py" "/Users/shyamkumarr@jmangroup.com/cicd"
         else
-          echo "Error: The file does not exist in DBFS."
-          exit 1
+            echo "Error: The file does not exist in DBFS."
+            exit 1
         fi
 
     - name: Configure Git and Push to GitHub
